In [0]:
import pandas as pd

In [0]:
df1 = pd.read_csv('TweetandReweetInformation_1.csv')
df2 = pd.read_csv('TweetandReweetInformation_2.csv')
df = pd.concat([df1, df2], ignore_index=True)

In [0]:
df

         Unnamed: 0  ...  Tweet_Language
0                 0  ...         English
1                 1  ...         English
2                 2  ...         Spanish
3                 3  ...         English
4                 4  ...         English
...             ...  ...             ...
1739838     1739838  ...         English
1739839     1739839  ...         English
1739840     1739840  ...         English
1739841     1739841  ...         English
1739842     1739842  ...         English

[1739843 rows x 7 columns]

In [0]:
df_result = df.groupby(['Tweet_Id','Tweet_Country','Retweet_Country']).count()[['Retweet_Id']]

In [0]:
df_result.rename(columns={"Retweet_Id":"Number_of_retweets"}, inplace=True)

In [0]:
df_result

                                                                       Number_of_retweets
Tweet_Id            Tweet_Country            Retweet_Country
682725898806677504  United States of America United States of America                   5
682751491346722817  United States of America Australia                                 38
                                             India                                      1
                                             New Zealand                                5
                                             United Kingdom                             4
...                                                                                   ...
1211454802170916866 United States of America United States of America                   2
1211460384126853120 United States of America United Kingdom                             1
1211466941661163521 United States of America United States of America                   1
1211487220143738880 United States of America Canada                                     1
1211495022564126720 United States of America United States of America                   1

[158770 rows x 1 columns]

In [0]:
df_result.to_csv('RetweetCountCountrywise.csv')